# Generated by Selenium IDE
import time
from datetime import datetime
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

def log_message(message, file):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"[{timestamp}] {message}"
    print(log_entry)
    file.write(log_entry + "\n")

class TestPriceComparison:
    def setup_method(self, method):
        service = Service(ChromeDriverManager().install())
        self.driver = webdriver.Chrome(service=service)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_price_comparison(self):
        with open("selenium_pricecomparison_test_results.txt", "w") as log_file:
            try:
                log_message("Starting the Selenium test for Price Comparison...", log_file)

                self.driver.get("http://127.0.0.1:8000/")
                self.driver.set_window_size(1095, 816)
                log_message("Navigated to the homepage.", log_file)

                self.driver.find_element(By.LINK_TEXT, "Login").click()
                log_message("Clicked on Login link.", log_file)

                self.driver.find_element(By.ID, "email").send_keys("ashmianees12@gmail.com")
                self.driver.find_element(By.ID, "password").send_keys("Ashmi@123")
                log_message("Entered login credentials.", log_file)

                self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
                log_message("Clicked login button.", log_file)

                WebDriverWait(self.driver, 10).until(
                    EC.presence_of_element_located((By.ID, "searchInput"))
                )
                self.driver.find_element(By.ID, "searchInput").send_keys("yellow parrot fish")
                log_message("Entered search term: yellow parrot fish.", log_file)

                self.driver.find_element(By.CSS_SELECTOR, ".fa-search").click()
                log_message("Clicked search button.", log_file)

                # Add any additional steps or assertions here

            except Exception as e:
                log_message(f"An error occurred: {e}", log_file)

            finally:
                time.sleep(3)  # Optional delay to observe the result
                self.driver.quit()
                log_message("Browser closed. Test completed.", log_file)

print("Test completed. Results have been written to selenium_pricecomparison_test_results.txt")
  
