# Generated by Django 5.1.1 on 2024-10-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_categoryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
