# Generated by Django 5.1.1 on 2024-10-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_complaint_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('id', 'shop')},
        ),
    ]
