# Generated by Django 5.0.6 on 2025-02-11 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0003_deliveryboy_is_first_login_deliveryboy_password_hash'),
        ('shop', '0012_product_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('delivery_boy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_system.deliveryboy')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='shop.order')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
