# Generated by Django 5.0.6 on 2025-02-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_is_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
