# Generated by Django 5.0.6 on 2025-03-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_decoration_fishspecies_plantspecies_watertype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoration',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fishspecies',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plantspecies',
            name='description',
        ),
        migrations.AlterField(
            model_name='aquariumdecoration',
            name='aquarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorations', to='shop.aquariumdesign'),
        ),
        migrations.AlterField(
            model_name='aquariumdecoration',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aquariumdecoration',
            name='position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aquariumdesign',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aquariumfish',
            name='aquarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish', to='shop.aquariumdesign'),
        ),
        migrations.AlterField(
            model_name='aquariumfish',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aquariumfish',
            name='position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aquariumplant',
            name='aquarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='shop.aquariumdesign'),
        ),
        migrations.AlterField(
            model_name='aquariumplant',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aquariumplant',
            name='position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='material',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fishcompatibility',
            name='compatibility_level',
            field=models.CharField(choices=[('compatible', 'Compatible'), ('caution', 'Caution'), ('incompatible', 'Incompatible')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='aggression_level',
            field=models.CharField(choices=[('peaceful', 'Peaceful'), ('semi-aggressive', 'Semi-Aggressive'), ('aggressive', 'Aggressive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='min_school_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='ph_max',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='ph_min',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='schooling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='temperature_max',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='temperature_min',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='growth_rate',
            field=models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='light_requirement',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watertype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watertype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
