# Generated by Django 5.0.6 on 2025-03-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_decoration_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fishspecies',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='decoration_images/'),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fish_images/'),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/'),
        ),
    ]
