# Generated by Django 5.0.6 on 2025-04-01 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0003_deliveryboy_is_first_login_deliveryboy_password_hash'),
        ('shop', '0020_decoration_description_fishspecies_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoration',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fishspecies',
            name='description',
        ),
        migrations.AlterField(
            model_name='decoration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='decorations/'),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fish_species/'),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_species/'),
        ),
        migrations.CreateModel(
            name='DeliveryBoyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deliveries_count', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='delivery_system.deliveryboy')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopdetails')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
