# Generated by Django 5.0.6 on 2025-04-02 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_decoration_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquariumPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for a standard size aquarium', max_digits=10)),
                ('base_length', models.IntegerField(help_text='Base length in inches for the standard price')),
                ('base_width', models.IntegerField(help_text='Base width in inches for the standard price')),
                ('base_height', models.IntegerField(help_text='Base height in inches for the standard price')),
                ('length_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier for length', max_digits=5)),
                ('width_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier for width', max_digits=5)),
                ('height_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier for height', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquarium_pricing', to='shop.shopdetails')),
            ],
        ),
    ]
