# Generated by Django 5.0.6 on 2025-01-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_chatbotknowledge_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotknowledge',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatbotknowledge',
            name='category',
            field=models.CharField(choices=[('general', 'General Information'), ('products', 'Products'), ('shops', 'Shops'), ('orders', 'Orders'), ('delivery', 'Delivery'), ('payment', 'Payment'), ('user', 'User Information')], max_length=50),
        ),
    ]
