# Generated by Django 5.0.6 on 2025-01-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_chatbotknowledge_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
    ]
