# Generated by Django 5.0.6 on 2025-01-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0012_product_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('vehicle_details', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('vehicle_details', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('shops', models.ManyToManyField(related_name='delivery_boys', to='shop.shopdetails')),
            ],
        ),
    ]
