# Generated by Django 5.0.6 on 2025-01-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='license',
            field=models.ImageField(null=True, upload_to='delivery_licenses/'),
        ),
        migrations.AddField(
            model_name='deliveryboyapplication',
            name='license',
            field=models.ImageField(default=1, upload_to='delivery_licenses/'),
            preserve_default=False,
        ),
    ]
