# Generated by Django 5.0.6 on 2025-02-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0002_deliveryboy_license_deliveryboyapplication_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='password_hash',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
